/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ElectricalRouteImport } from './routes/electrical'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as PowerFlowRouteImport } from './routes/power-flow'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'
import { Route as HvacCassetteRouteImport } from './routes/hvac.cassette'
import { Route as HvacVavRouteImport } from './routes/hvac.vav'
import { Route as UpsIndexRouteImport } from './routes/ups.index'
import { Route as UpsIdRouteImport } from './routes/ups.$id'
import { Route as HvacAhuIndexRouteImport } from './routes/hvac.ahu.index'
import { Route as HvacAhuIdRouteImport } from './routes/hvac.ahu.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalRoute = ElectricalRouteImport.update({
  id: '/electrical',
  path: '/electrical',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerFlowRoute = PowerFlowRouteImport.update({
  id: '/power-flow',
  path: '/power-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacCassetteRoute = HvacCassetteRouteImport.update({
  id: '/hvac/cassette',
  path: '/hvac/cassette',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacVavRoute = HvacVavRouteImport.update({
  id: '/hvac/vav',
  path: '/hvac/vav',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsIndexRoute = UpsIndexRouteImport.update({
  id: '/ups/',
  path: '/ups/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsIdRoute = UpsIdRouteImport.update({
  id: '/ups/$id',
  path: '/ups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacAhuIndexRoute = HvacAhuIndexRouteImport.update({
  id: '/hvac/ahu/',
  path: '/hvac/ahu/',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacAhuIdRoute = HvacAhuIdRouteImport.update({
  id: '/hvac/ahu/$id',
  path: '/hvac/ahu/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/electrical': typeof ElectricalRoute
  '/energy': typeof EnergyRoute
  '/explorer': typeof ExplorerRoute
  '/power-flow': typeof PowerFlowRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/hvac/cassette': typeof HvacCassetteRoute
  '/hvac/vav': typeof HvacVavRoute
  '/ups/$id': typeof UpsIdRoute
  '/ups/': typeof UpsIndexRoute
  '/hvac/ahu/$id': typeof HvacAhuIdRoute
  '/hvac/ahu/': typeof HvacAhuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/electrical': typeof ElectricalRoute
  '/energy': typeof EnergyRoute
  '/explorer': typeof ExplorerRoute
  '/power-flow': typeof PowerFlowRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/hvac/cassette': typeof HvacCassetteRoute
  '/hvac/vav': typeof HvacVavRoute
  '/ups/$id': typeof UpsIdRoute
  '/ups': typeof UpsIndexRoute
  '/hvac/ahu/$id': typeof HvacAhuIdRoute
  '/hvac/ahu': typeof HvacAhuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/electrical': typeof ElectricalRoute
  '/energy': typeof EnergyRoute
  '/explorer': typeof ExplorerRoute
  '/power-flow': typeof PowerFlowRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/hvac/cassette': typeof HvacCassetteRoute
  '/hvac/vav': typeof HvacVavRoute
  '/ups/$id': typeof UpsIdRoute
  '/ups/': typeof UpsIndexRoute
  '/hvac/ahu/$id': typeof HvacAhuIdRoute
  '/hvac/ahu/': typeof HvacAhuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarms'
    | '/analytics'
    | '/audit'
    | '/electrical'
    | '/energy'
    | '/explorer'
    | '/power-flow'
    | '/reports'
    | '/settings'
    | '/users'
    | '/hvac/cassette'
    | '/hvac/vav'
    | '/ups/$id'
    | '/ups/'
    | '/hvac/ahu/$id'
    | '/hvac/ahu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarms'
    | '/analytics'
    | '/audit'
    | '/electrical'
    | '/energy'
    | '/explorer'
    | '/power-flow'
    | '/reports'
    | '/settings'
    | '/users'
    | '/hvac/cassette'
    | '/hvac/vav'
    | '/ups/$id'
    | '/ups'
    | '/hvac/ahu/$id'
    | '/hvac/ahu'
  id:
    | '__root__'
    | '/'
    | '/alarms'
    | '/analytics'
    | '/audit'
    | '/electrical'
    | '/energy'
    | '/explorer'
    | '/power-flow'
    | '/reports'
    | '/settings'
    | '/users'
    | '/hvac/cassette'
    | '/hvac/vav'
    | '/ups/$id'
    | '/ups/'
    | '/hvac/ahu/$id'
    | '/hvac/ahu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmsRoute: typeof AlarmsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  ElectricalRoute: typeof ElectricalRoute
  EnergyRoute: typeof EnergyRoute
  ExplorerRoute: typeof ExplorerRoute
  PowerFlowRoute: typeof PowerFlowRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  HvacCassetteRoute: typeof HvacCassetteRoute
  HvacVavRoute: typeof HvacVavRoute
  UpsIdRoute: typeof UpsIdRoute
  UpsIndexRoute: typeof UpsIndexRoute
  HvacAhuIdRoute: typeof HvacAhuIdRoute
  HvacAhuIndexRoute: typeof HvacAhuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical': {
      id: '/electrical'
      path: '/electrical'
      fullPath: '/electrical'
      preLoaderRoute: typeof ElectricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-flow': {
      id: '/power-flow'
      path: '/power-flow'
      fullPath: '/power-flow'
      preLoaderRoute: typeof PowerFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac/cassette': {
      id: '/hvac/cassette'
      path: '/hvac/cassette'
      fullPath: '/hvac/cassette'
      preLoaderRoute: typeof HvacCassetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac/vav': {
      id: '/hvac/vav'
      path: '/hvac/vav'
      fullPath: '/hvac/vav'
      preLoaderRoute: typeof HvacVavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ups/': {
      id: '/ups/'
      path: '/ups'
      fullPath: '/ups/'
      preLoaderRoute: typeof UpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ups/$id': {
      id: '/ups/$id'
      path: '/ups/$id'
      fullPath: '/ups/$id'
      preLoaderRoute: typeof UpsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac/ahu/': {
      id: '/hvac/ahu/'
      path: '/hvac/ahu'
      fullPath: '/hvac/ahu/'
      preLoaderRoute: typeof HvacAhuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac/ahu/$id': {
      id: '/hvac/ahu/$id'
      path: '/hvac/ahu/$id'
      fullPath: '/hvac/ahu/$id'
      preLoaderRoute: typeof HvacAhuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmsRoute: AlarmsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  ElectricalRoute: ElectricalRoute,
  EnergyRoute: EnergyRoute,
  ExplorerRoute: ExplorerRoute,
  PowerFlowRoute: PowerFlowRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  HvacCassetteRoute: HvacCassetteRoute,
  HvacVavRoute: HvacVavRoute,
  UpsIdRoute: UpsIdRoute,
  UpsIndexRoute: UpsIndexRoute,
  HvacAhuIdRoute: HvacAhuIdRoute,
  HvacAhuIndexRoute: HvacAhuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
